# The settings here are automatically set by my configuration during initialization.
# Do not edit this file unless you know what you're doing.
{ host }:

{
  # These attributes are properties related to the host system itself.
  system = {
    # The name of this host.
    name = host;

    # The initial version of NixOS installed on this machine.
    # This is used to set 'system.stateVersion'.
    version = "24.05";

    # The platform says what processor architecture and operating system this host uses.
    # This is used to determine which packages are available for this host to use.
    platform = "x86_64-linux";
  };
}
